### ISSUE TITLE
limit height of images in profiles

### ISSUE THREAD

**Issue by ticoombs** [sunaurus/lemmy-ui-next#2]
- Example: https://next.reddthat.com/u/reddthat

Currently it takes up the whole screen rather than the 240px of the middle (which is what the current lemmy-ui does)

**Comment by sunaurus** [comment]
Limited banners to a max height of 360px in v0.7.3, it's a bit bigger than default lemmy-ui, but seems to work better (subjectively) for most communities and users I checked. Thanks for the report!
